##### current data predictions (direction and speed) #####
# NOTES:
# Obtained for 2 DFO stations - Wayton Pass and Blackney Pass
# Data look like:
# Date      YYYY/MM/DD
# HourMinute      hhmm
# Direction      deg T
# Speed            m/s

# WEYNTON PASSAGE station  is at 50 36.2 N,  126 48.7 W   
# BLACKNEY PASSAGE station is at 50 33.3 N,  126 41.052 W   

# Significant bits of this code generated by ChatGPT. 
# Created Dec, 2025
#
# UPDATED: 
# 2026/06/23: Added tide heights to compare tidal cycle with temperature
#
############################################################################

#------ Data loading section ----

# get the tidal current files ... 
current_files <- list.files( path = paste0(source_dir, "/tidalflow"),
                             pattern = "\\.cu05$",
                             full.names = TRUE )

black_curr <- load_currents( current_files[1] )
weynt_curr <- load_currents( current_files[2] )

black_curr$Dataset <- "Blackney Pass"
weynt_curr$Dataset <- "Weynton Pass"

# get the tide heights for Alert Bay
tide_file <- paste0(source_dir, "/tidalflow/", 
                                "Annual_Predictions_Alert Bay_2025.csv")

tides <- read.csv( tide_file, header = TRUE)
names(tides) <- c("DateTime", "Metres")

tides$DateTime <- as.POSIXct(tides$DateTime, format = "%Y-%m-%dT%H:%M:%S", tz = "UTC")
tides$Metres   <- as.numeric(as.character(tides$Metres))
head( tides$DateTime )



#---------------------
# Prep tidal data for regression fitting to get a good fitting curve. 

# Convert DateTime to numeric hours from start (model needs numeric time)
t0 <- min(tides$DateTime)
tides$hours <- as.numeric(difftime(tides$DateTime, t0, units = "hours"))

# Tidal constituent periods (hours)
M2 <- 12.4206
S2 <- 12.0000
K1 <- 23.9345
O1 <- 25.8194

# Build harmonic regression
# Each constituent gets a sin + cos pair (handles amplitude and phase)
harm_fit <- lm(Metres ~ 
                 sin(2*pi*hours/M2) + cos(2*pi*hours/M2) +
                 sin(2*pi*hours/S2) + cos(2*pi*hours/S2) +
                 sin(2*pi*hours/K1) + cos(2*pi*hours/K1) +
                 sin(2*pi*hours/O1) + cos(2*pi*hours/O1),
               data = tides)

summary(harm_fit)

# Predict on a fine grid for smooth curve
hours_fine <- seq(min(tides$hours), max(tides$hours), by = 0.25)
tpred_df <- data.frame(hours = hours_fine)
tpred_df$DateTime <- t0 + hours_fine * 3600
tpred_df$fit <- predict(harm_fit, newdata = tpred_df)

# Fitted tidal plot ... 
ggplot() +
  geom_point(data = tides, aes(x = DateTime, y = Metres), 
             size = 0.8, colour = "grey50") +
  geom_line(data = pred_df, aes(x = DateTime, y = fit),
            colour = "steelblue", linewidth = 0.8) +
  labs(x = "Date", y = "Water Level (m)",
       title = "Alert Bay — Harmonic Tidal Fit (M2, S2, K1, O1)")



#---- Tidal stuff above




#----- Plotting currents -----
# Lets look at just a week of data ... 
x <- black_curr[ black_curr$Timestamp > as.POSIXct("2025-07-15", tz = "UTC") & 
                 black_curr$Timestamp < as.POSIXct("2025-07-22", tz = "UTC"), ]

y <- weynt_curr[ weynt_curr$Timestamp > as.POSIXct("2025-07-15", tz = "UTC") & 
                 weynt_curr$Timestamp < as.POSIXct("2025-07-22", tz = "UTC"), ]

plot_dat <- rbind(x, y)

# Column to plot, y axis title, and main title are parameters
# Required values include "Timestamp" and "Dataset"
two_series_plot( plot_dat, "Speed", "Current speed", "Tidal current speed" )


x <- black_curr[  black_curr$Timestamp < as.POSIXct("2025-01-03", tz = "UTC"), ]


#---- Turning times ----

# Add transition times to the dataframes 
x <- classify_ebb_flood( black_curr )
table( x$FlowState )

y <- detect_transitions( x )

z <- make_flow_windows( y )
write.csv( z, file = paste0(results_dir, "/tide_windows_blackney.csv") )




#----  Plot flow windows with the mooring CO2 plotting data sets ----

# copied from CO2_data_loadings so can adjust dates 
sdate <- "2025-07-15"
edate <- "2025-07-22"

f_dat <- focal_dat[ focal_dat$Timestamp > as.POSIXct(sdate, tz = "UTC") & 
                      focal_dat$Timestamp < as.POSIXct(edate, tz = "UTC"), ]

r_dat <- ref_dat[ ref_dat$Timestamp > as.POSIXct(sdate, tz = "UTC") & 
                    ref_dat$Timestamp < as.POSIXct(edate, tz = "UTC"), ]

CO2_dat <- rbind(f_dat, r_dat)

z_dat <- z[ z$StartTime >= as.POSIXct(sdate, tz = "UTC") & 
            z$EndTime   <= as.POSIXct(edate, tz = "UTC"), ]

#---- Plot of CO2 from moorings against background tidal flow state (ebb, flood) ----  
ggplot() +
  # Shaded ebb/flood windows
  geom_rect(
    data = z_dat,
    aes(
      xmin =  StartTime,
      xmax =  EndTime,
      ymin = -Inf,
      ymax = Inf,
      fill = Flow
    ),
    alpha = 0.5,          # transparency
    inherit.aes = FALSE
  ) +
  geom_line( data=CO2_dat, 
             aes(x = Timestamp, y = CO2, color = Dataset),
             size=1.2) +
  
  scale_fill_manual(
    values = c(
      "ebb"   = "steelblue",
      "flood" = "olivedrab2",
      "other" = "black"
    )
  ) +
  
  labs(
      x = "Time",
      y = expression(CO[2] ~ "(" * mu * "atm" * ")"),
      fill = "Flow State",
      color = "Dataset",
      title = "2 weeks of CO2 mooring data showing tidal ebb and flow windows"
    ) +
  
    theme_bw()



# Working with flow windows from above ... 

a <- speed_by_window( z_dat, black_curr[ c("Timestamp", "Speed")] )

plot( a$avg_speed ~ a$StartTime, type = "l" )



#---- FUNCTIONS ----
load_currents <- function(filename, tz = "UTC") {
  
  # Read all lines
  lines <- readLines(filename)
  
  # Identify first data line (starts with YYYY/MM/DD)
  data_start <- grep("^\\d{4}/\\d{2}/\\d{2}", lines)[1]
  if (is.na(data_start)) {
    stop("No data lines found in file: ", filename)
  }
  
  # Read only the data portion
  df <- read.table( text = lines[data_start:length(lines)],
                    header = FALSE,
                    col.names = c("Date", "HourMinute", "Direction", "Speed"),
                    stringsAsFactors = FALSE )
  
  # Build "YYYY/MM/DD HHMM" string
  time_str <- paste(df$Date, df$HourMinute) # need the space btwn date and time

  # Create POSIXct datetime
  df$Timestamp <- as.POSIXct(time_str, format = "%Y/%m/%d %H:%M", tz = tz)
  
  # Reorder columns
  df <- df[, c("Timestamp", "Date", "HourMinute", "Direction", "Speed")]
  
  return(df)
}


classify_ebb_flood <- function(df,
                               flood_range = c(315, 45),
                               ebb_range   = c(135, 225)) {
  
  dir <- df$Direction
  
  # Flood sector spans across 360 → handle wrap-around
  in_flood <- (dir >= flood_range[1] | dir <= flood_range[2])
  in_ebb   <- (dir >= ebb_range[1]   & dir <= ebb_range[2])
  
  state <- ifelse(in_flood, "flood",
                  ifelse(in_ebb, "ebb", "other"))
  
  df$FlowState <- state
  df
}

detect_transitions <- function(df) {
  state <- df$FlowState
  
  # Lagged state for comparison
  prev_state <- dplyr::lag(state)
  
  transitions <- which(state != prev_state & !is.na(prev_state))
  
  tibble::tibble(
    Timestamp  = df$Timestamp[transitions],
    From       = prev_state[transitions],
    To         = state[transitions]
  )
}

make_flow_windows <- function( transitions, series_start = NULL, series_end = NULL) {
  stopifnot(all(c("Timestamp", "From", "To") %in% names(transitions)))
  
  # Ensure sorted by time
  tr <- transitions[order(transitions$Timestamp), ]
  
  # 1) Collapse 'other' bridges into single ebb<->flood transitions
  collapsed <- list()
  i <- 1
  n <- nrow(tr)
  
  while (i <= n) {
    # Pattern: X -> other  then  other -> Y
    if (tr$To[i] == "other" && i < n && tr$From[i + 1] == "other") {
      from_state <- tr$From[i]
      to_state   <- tr$To[i + 1]      # should be 'ebb' or 'flood'
      t1 <- tr$Timestamp[i]
      t2 <- tr$Timestamp[i + 1]
      mid_time <- t1 + (t2 - t1) / 2  # midpoint
      
      collapsed[[length(collapsed) + 1]] <- data.frame(
        Timestamp = mid_time,
        From = from_state,
        To   = to_state,
        stringsAsFactors = FALSE
      )
      i <- i + 2  # skip the pair
    } else if (tr$From[i] != "other" && tr$To[i] != "other") {
      # Keep direct ebb<->flood transitions
      collapsed[[length(collapsed) + 1]] <- tr[i, ]
      i <- i + 1
    } else {
      # Transitions involving 'other' at start/end that we can't bridge cleanly
      i <- i + 1
    }
  }
  
  if (length(collapsed) == 0) {
    stop("No usable ebb/flood transitions after collapsing 'other' states.")
  }
  
  tr2 <- do.call(rbind, collapsed)
  tr2 <- tr2[order(tr2$Timestamp), ]
  
  # 2) Build ebb/flood windows
  
  # If user didn't give start/end, default to first/last transition times
  if (is.null(series_start)) series_start <- tr2$Timestamp[1]
  if (is.null(series_end))   series_end   <- tr2$Timestamp[nrow(tr2)]
  
  starts <- c()
  ends   <- c()
  flows  <- c()
  
  cur_state <- tr2$From[1]
  cur_start <- series_start
  
  for (k in seq_len(nrow(tr2))) {
    t_k <- tr2$Timestamp[k]
    
    # Close current window at this transition time
    starts <- c(starts, cur_start)
    ends   <- c(ends, t_k)
    flows  <- c(flows, cur_state)
    
    # New state starts at this time
    cur_state <- tr2$To[k]
    cur_start <- t_k
  }
  
  # Final window from last transition to series_end
  if (series_end > cur_start) {
    starts <- c(starts, cur_start)
    ends   <- c(ends, series_end)
    flows  <- c(flows, cur_state)
  }
  out <- data.frame(
    StartTime = as.POSIXct(starts, tz = "UTC"),
    EndTime   = as.POSIXct(ends, tz = "UTC"),
    Flow      = flows,
    stringsAsFactors = FALSE
  )
  out
}


speed_by_window <- function(windows, tide) {
  
  # Ensure time columns are POSIXct
  windows$StartTime <- as.POSIXct(windows$StartTime, tz = "UTC")
  windows$EndTime   <- as.POSIXct(windows$EndTime,   tz = "UTC")
  tide$Timestamp    <- as.POSIXct(tide$Timestamp,    tz = "UTC")
  
  # Prepare output columns
  avg_speed <- numeric(nrow(windows))
  sd_speed  <- numeric(nrow(windows))
  n_points  <- integer(nrow(windows))
  
  # Loop through each window
  for (i in seq_len(nrow(windows))) {
    
    start_i <- windows$StartTime[i]
    end_i   <- windows$EndTime[i]
    
    # Logical mask for data in this window
    sel <- tide$Timestamp >= start_i & tide$Timestamp < end_i
    
    speeds <- tide$Speed[sel]
    
    if (length(speeds) == 0) {
      avg_speed[i] <- NA
      sd_speed[i]  <- NA
      n_points[i]  <- 0
    } else {
      avg_speed[i] <- mean(speeds, na.rm = TRUE)
      sd_speed[i]  <- sd(speeds, na.rm = TRUE)
      n_points[i]  <- length(speeds)
    }
  }
  
  # Return a combined data frame
  out <- cbind(
    windows,
    avg_speed = avg_speed,
    sd_speed  = sd_speed,
    n_points  = n_points
  )
  
  return(out)
}




