##### current data predictions (direction and speed) #####
# Obtained for 2 DFO stations - Wayton Pass and Blackney Pass
# Data look like:
# Date      YYYY/MM/DD
# HourMinute      hhmm
# Direction      deg T
# Speed            m/s

# WEYNTON PASSAGE station  is at 50 36.2 N,  126 48.7 W   
# BLACKNEY PASSAGE station is at 50 33.3 N,  126 41.052 W   

# Significant bits of this code generated by ChatGPT. 
# Created Dec, 2025
############################################################################

#------ Data loading section ----

# get all the files ... 
current_files <- list.files( path = paste0(source_dir, "/tidalflow"),
                             pattern = "\\.cu05$",
                             full.names = TRUE )

black_curr <- load_currents( current_files[1] )
weynt_curr <- load_currents( current_files[2] )


black_curr$Dataset <- "Blackney Pass"
weynt_curr$Dataset <- "Weynton Pass"


# Lets look at just a week of data ... 
x <- black_curr[ black_curr$Timestamp > as.POSIXct("2025-07-15", tz = "UTC") & 
                 black_curr$Timestamp < as.POSIXct("2025-07-22", tz = "UTC"), ]

y <- weynt_curr[ weynt_curr$Timestamp > as.POSIXct("2025-07-15", tz = "UTC") & 
                 weynt_curr$Timestamp < as.POSIXct("2025-07-22", tz = "UTC"), ]

plot_dat <- rbind(x, y)

# Column to plot, y axis title, and main title are parameters
# Required values include "Timestamp" and "Dataset"
two_series_plot( plot_dat, "Speed", "Current speed", "Tidal current speed" )


x <- black_curr[  black_curr$Timestamp < as.POSIXct("2025-01-03", tz = "UTC"), ]


#---- Turning times ----

# Add transition times to the dataframes 
x <- classify_ebb_flood( black_curr )
table( x$FlowState )

y <- detect_transitions( x )


z <- make_flow_windows( y )



#----  Plot flow windows with the mooring CO2 plotting data sets ----

# copied from CO2_data_loadings so can adjust dates 
sdate <- "2025-07-15"
edate <- "2025-07-22"

f_dat <- focal_dat[ focal_dat$Timestamp > as.POSIXct(sdate, tz = "UTC") & 
                      focal_dat$Timestamp < as.POSIXct(edate, tz = "UTC"), ]

r_dat <- ref_dat[ ref_dat$Timestamp > as.POSIXct(sdate, tz = "UTC") & 
                    ref_dat$Timestamp < as.POSIXct(edate, tz = "UTC"), ]

CO2_dat <- rbind(f_dat, r_dat)

z_dat <- z[ z$StartTime >= as.POSIXct(sdate, tz = "UTC") & 
            z$EndTime   <= as.POSIXct(edate, tz = "UTC"), ]


# Make a da plot .. 
ggplot() +
  # Shaded ebb/flood windows
  geom_rect(
    data = z_dat,
    aes(
      xmin =  StartTime,
      xmax =  EndTime,
      ymin = -Inf,
      ymax = Inf,
      fill = Flow
    ),
    alpha = 0.5,          # transparency
    inherit.aes = FALSE
  ) +
  geom_line( data=CO2_dat, 
             aes(x = Timestamp, y = CO2, color = Dataset),
             size=1.2) +
  
  scale_fill_manual(
    values = c(
      "ebb"   = "steelblue",
      "flood" = "olivedrab2",
      "other" = "black"
    )
  ) +
  
  labs(
      x = "Time",
      y = expression(CO[2] ~ "(" * mu * "atm" * ")"),
      fill = "Flow State",
      color = "Dataset",
      title = "2 weeks of CO2 mooring data showing tidal ebb and flow windows"
    ) +
  
    theme_bw()





#---- FUNCTIONS ----
load_currents <- function(filename, tz = "UTC") {
  
  # Read all lines
  lines <- readLines(filename)
  
  # Identify first data line (starts with YYYY/MM/DD)
  data_start <- grep("^\\d{4}/\\d{2}/\\d{2}", lines)[1]
  if (is.na(data_start)) {
    stop("No data lines found in file: ", filename)
  }
  
  # Read only the data portion
  df <- read.table( text = lines[data_start:length(lines)],
                    header = FALSE,
                    col.names = c("Date", "HourMinute", "Direction", "Speed"),
                    stringsAsFactors = FALSE )
  
  # Build "YYYY/MM/DD HHMM" string
  time_str <- paste(df$Date, df$HourMinute) # need the space btwn date and time

  # Create POSIXct datetime
  df$Timestamp <- as.POSIXct(time_str, format = "%Y/%m/%d %H:%M", tz = tz)
  
  # Reorder columns
  df <- df[, c("Timestamp", "Date", "HourMinute", "Direction", "Speed")]
  
  return(df)
}


classify_ebb_flood <- function(df,
                               flood_range = c(315, 45),
                               ebb_range   = c(135, 225)) {
  
  dir <- df$Direction
  
  # Flood sector spans across 360 → handle wrap-around
  in_flood <- (dir >= flood_range[1] | dir <= flood_range[2])
  in_ebb   <- (dir >= ebb_range[1]   & dir <= ebb_range[2])
  
  state <- ifelse(in_flood, "flood",
                  ifelse(in_ebb, "ebb", "other"))
  
  df$FlowState <- state
  df
}

detect_transitions <- function(df) {
  state <- df$FlowState
  
  # Lagged state for comparison
  prev_state <- dplyr::lag(state)
  
  transitions <- which(state != prev_state & !is.na(prev_state))
  
  tibble::tibble(
    Timestamp  = df$Timestamp[transitions],
    From       = prev_state[transitions],
    To         = state[transitions]
  )
}

make_flow_windows <- function( transitions, series_start = NULL, series_end = NULL) {
  stopifnot(all(c("Timestamp", "From", "To") %in% names(transitions)))
  
  # Ensure sorted by time
  tr <- transitions[order(transitions$Timestamp), ]
  
  # 1) Collapse 'other' bridges into single ebb<->flood transitions
  collapsed <- list()
  i <- 1
  n <- nrow(tr)
  
  while (i <= n) {
    # Pattern: X -> other  then  other -> Y
    if (tr$To[i] == "other" && i < n && tr$From[i + 1] == "other") {
      from_state <- tr$From[i]
      to_state   <- tr$To[i + 1]      # should be 'ebb' or 'flood'
      t1 <- tr$Timestamp[i]
      t2 <- tr$Timestamp[i + 1]
      mid_time <- t1 + (t2 - t1) / 2  # midpoint
      
      collapsed[[length(collapsed) + 1]] <- data.frame(
        Timestamp = mid_time,
        From = from_state,
        To   = to_state,
        stringsAsFactors = FALSE
      )
      i <- i + 2  # skip the pair
    } else if (tr$From[i] != "other" && tr$To[i] != "other") {
      # Keep direct ebb<->flood transitions
      collapsed[[length(collapsed) + 1]] <- tr[i, ]
      i <- i + 1
    } else {
      # Transitions involving 'other' at start/end that we can't bridge cleanly
      i <- i + 1
    }
  }
  
  if (length(collapsed) == 0) {
    stop("No usable ebb/flood transitions after collapsing 'other' states.")
  }
  
  tr2 <- do.call(rbind, collapsed)
  tr2 <- tr2[order(tr2$Timestamp), ]
  
  # 2) Build ebb/flood windows
  
  # If user didn't give start/end, default to first/last transition times
  if (is.null(series_start)) series_start <- tr2$Timestamp[1]
  if (is.null(series_end))   series_end   <- tr2$Timestamp[nrow(tr2)]
  
  starts <- c()
  ends   <- c()
  flows  <- c()
  
  cur_state <- tr2$From[1]
  cur_start <- series_start
  
  for (k in seq_len(nrow(tr2))) {
    t_k <- tr2$Timestamp[k]
    
    # Close current window at this transition time
    starts <- c(starts, cur_start)
    ends   <- c(ends, t_k)
    flows  <- c(flows, cur_state)
    
    # New state starts at this time
    cur_state <- tr2$To[k]
    cur_start <- t_k
  }
  
  # Final window from last transition to series_end
  if (series_end > cur_start) {
    starts <- c(starts, cur_start)
    ends   <- c(ends, series_end)
    flows  <- c(flows, cur_state)
  }
  out <- data.frame(
    StartTime = as.POSIXct(starts, tz = "UTC"),
    EndTime   = as.POSIXct(ends, tz = "UTC"),
    Flow      = flows,
    stringsAsFactors = FALSE
  )
  out
}






